[package]
name = "swap_router"
version = "1.0.0"
authors = []

[addresses]
# Mainnet deployer wallet: 2026-04-13
# Previous address: 0x61ed30854e689da3c31d2e07b55fd94add415aac102d2dd7f831bf5c294757e3
swap_router = "0x2a5b1aad1cb52fa0f2be5da258cd85aa340f55bccd8cf684f89dbc6f5cbe0a69"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

