const LANGUAGE_KEY = "language";
const GLOBAL_SETTINGS_KEY = "settings_global";

export const SUPPORTED_LANGUAGES = ["en", "zh", "ko", "tr"];

const normalizeLanguage = (value) => {
  const candidate = String(value || "").toLowerCase();
  return SUPPORTED_LANGUAGES.includes(candidate) ? candidate : "en";
};

export const getStoredLanguagePreference = (settingsKey = null) => {
  if (typeof window === "undefined") return "en";

  if (settingsKey) {
    try {
      const scopedRaw = window.localStorage.getItem(settingsKey);
      if (scopedRaw) {
        const scoped = JSON.parse(scopedRaw);
        return normalizeLanguage(scoped?.language);
      }
    } catch {
      // ignore malformed localStorage
    }
  }

  try {
    const globalRaw = window.localStorage.getItem(GLOBAL_SETTINGS_KEY);
    if (globalRaw) {
      const globalSettings = JSON.parse(globalRaw);
      const lang = normalizeLanguage(globalSettings?.language);
      if (lang) return lang;
    }
  } catch {
    // ignore malformed localStorage
  }

  return normalizeLanguage(window.localStorage.getItem(LANGUAGE_KEY));
};

export const saveLanguagePreference = (language, settingsKey = null) => {
  const normalized = normalizeLanguage(language);

  if (typeof window === "undefined") {
    return normalized;
  }

  window.localStorage.setItem(LANGUAGE_KEY, normalized);

  try {
    const globalRaw = window.localStorage.getItem(GLOBAL_SETTINGS_KEY);
    const globalSettings = globalRaw ? JSON.parse(globalRaw) : {};
    globalSettings.language = normalized;
    window.localStorage.setItem(GLOBAL_SETTINGS_KEY, JSON.stringify(globalSettings));
  } catch {
    window.localStorage.setItem(GLOBAL_SETTINGS_KEY, JSON.stringify({ language: normalized }));
  }

  if (settingsKey) {
    try {
      const scopedRaw = window.localStorage.getItem(settingsKey);
      const scopedSettings = scopedRaw ? JSON.parse(scopedRaw) : {};
      scopedSettings.language = normalized;
      window.localStorage.setItem(settingsKey, JSON.stringify(scopedSettings));
    } catch {
      window.localStorage.setItem(settingsKey, JSON.stringify({ language: normalized }));
    }
  }

  window.dispatchEvent(
    new CustomEvent("languagechange", {
      detail: { language: normalized },
    })
  );

  return normalized;
};

const TRANSLATIONS = {
  en: {
    navPortfolio: "PORTFOLIO",
    navSwap: "SWAP",
    navBadges: "BADGES",
    navLeaderboard: "LEADERBOARD",
    navMore: "MORE",
    menuSupport: "Support",
    menuTheme: "Theme",
    menuSettings: "Settings",
    menuResources: "Resources",
    searchPlaceholder: "Search address / username / move id",
    recentSearches: "Recent Searches",
    searchBlockchain: "Searching blockchain...",
    noProfilesFound: "No profiles found. Enter a valid 0x address to search the blockchain.",
    lookupOnChain: "Look up {address} on-chain",
    walletAddress: "Wallet address",
    onChain: "On-chain",
    profile: "Profile",
    address: "Address",
    connectWallet: "Connect Wallet",
    disconnect: "Disconnect",
    settingsTitle: "Settings",
    settingsSubtitle: "Customize your portfolio experience",
    backToPortfolio: "Back to Portfolio",
    display: "Display",
    currency: "Currency",
    currencyDescription: "Choose your preferred currency",
    theme: "Theme",
    themeDescription: "Select your theme preference",
    language: "Language",
    languageDescription: "Choose your language",
    hidePositions: "Hide positions",
    hidePositionsDescription: "Hide DeFi and LP positions below a USD threshold",
    notifications: "Notifications",
    enableNotifications: "Enable Notifications",
    enableNotificationsDescription: "Receive updates about your portfolio",
    priceAlerts: "Price Alerts",
    priceAlertsDescription: "Get notified of significant price changes",
    advanced: "Advanced",
    showTestnet: "Show Testnet",
    showTestnetDescription: "Include testnet tokens in portfolio",
    resetDefault: "Reset to Default",
    saveSettings: "Save Settings",
    dark: "Dark",
    light: "Light",
    auto: "Auto",
    english: "English",
    chinese: "Chinese",
    korean: "Korean",
    turkish: "Turkish",
    homeTitleLead: "Your Complete",
    homeTitleAccent: " DeFi Portfolio",
    homeSubtitle: "Track, analyze, and manage your Movement Network assets in real time. Monitor DeFi positions, token balances, and portfolio activity all in one place.",
    homeProtocolsSupported: "Protocols Supported",
    homeRealtimeData: "On-chain Data",
    homePortfolioTracking: "Portfolio Tracking",
    homeConnectWalletPrompt: "or connect your wallet",
    homeChooseWallet: "Choose Wallet",
    homeFeatureAnalyticsTitle: "Portfolio Analytics",
    homeFeatureAnalyticsDesc: "Track your complete portfolio with real time balance updates and historical performance charts",
    homeFeatureDefiTitle: "DeFi Positions",
    homeFeatureDefiDesc: "Monitor lending, staking, and liquidity positions across all Movement protocols",
    homeFeaturePricesTitle: "Live Prices",
    homeFeaturePricesDesc: "Get accurate token pricing with automatic USD conversion and market data",
    homeFeatureSwapTitle: "Token Swaps",
    homeFeatureSwapDesc: "Seamlessly swap tokens within the app with competitive rates and low fees",
    homeFooterTitle: "Movement Portfolio Tracker",
    homeFooterBuiltOn: "Built on Movement",
    moreTitle: "More",
    moreSupport: "Support",
    moreResources: "Resources",
    moreTerms: "Terms Of Business",
    morePrivacy: "Privacy Policy",
    leaderboardTitle: "Leaderboard",
    leaderboardEmpty: "No leaderboard available yet",
    profileTitle: "Your Profile",
    profileBasicInfo: "Basic Information",
    profileSocialLinks: "Social Links",
    profileDisplayName: "Display Name",
    profileDisplayNamePlaceholder: "Enter your display name",
    profileBio: "Bio",
    profileBioPlaceholder: "Tell us about yourself...",
    profileSave: "Save Profile",
    profileSaving: "Saving...",
    profileUploadPhoto: "Upload Photo",
    profileChangePhoto: "Change Photo",
    profileRemovePhoto: "Remove",
    profileProfileCreated: "Profile Created",
    profileLastUpdated: "Last Updated",
    profileProfileViews: "Profile Views",
    profileComingSoon: "Coming Soon",
    profileSaveFailed: "Failed to save profile: ",
    profileSavedSuccess: "Profile saved successfully!",
    profileLevel: "Level",
    profileViewInvalid: "Invalid Profile",
    profileViewBackToPortfolio: "Back to Portfolio",
    profileViewLoading: "Loading profile...",
    profileViewInfo: "Profile Information",
    profileViewAddress: "Address",
    profileViewNoProfileTitle: "No Profile Found",
    profileViewNoProfileBody: "This address doesn't have a profile yet.",
    portfolioTabWalletBalance: "Wallet Balance",
    portfolioTabDefiPositions: "DeFi Positions",
    portfolioTabLp: "LP",
    portfolioTabTrxHistory: "Transactions",
    portfolioTransactionHistory: "Transaction History",
    badgesTitle: "Badges",
    badgesSubtitle: "Earn SBT achievements by participating in the Movement Network.",
    badgesAchievements: "Achievements",
    badgesEarned: "{earned} of {total} Earned",
    badgesDeepScan: "Deep Scan My Wallet",
    badgesScanning: "⚡ Scanning Network...",
    badgesRefresh: "Refresh",
    badgesActive: "Active",
    badgesExpired: "Expired",
    badgesCompleted: "Completed",
    badgesCompletedNote: "Achievements are updated weekly.",
    badgesIncomplete: "Incomplete",
    badgesIncompleteNote: "Keep trading to unlock more.",
    badgesChecking: "Checking eligibility...",
    badgesEligible: "Eligible",
    badgesClaim: "Claim Badge",
    badgesClaiming: "Claiming...",
    badgesOwned: "You own this badge ✓",
    badgesLocked: "Locked",
    badgesNotEligible: "Not eligible yet",
    badgesRecheck: "Re-check",
    badgesRetry: "Retry",
    badgesCheckFailed: "Check failed — try again",
    badgesShare: "Share achievement",
    badgesReadyToClaim: "Ready to claim",
    badgesInProgress: "In progress",
    swapTitle: "Swap",
    swapSettings: "Swap Settings",
    swapMosaicExec: "Mosaic execution controls",
    swapSlippageTolerance: "Slippage Tolerance",
    swapCurrentSlippage: "Current: {slippage}%",
    swapHighSlippageWarning: "High slippage may result in unfavorable execution.",
    swapAggregator: "Aggregator",
    swapProviderCount: "Provider: 1/1",
    swapMosaicAggregatorNote: "Mosaic is the fixed aggregator for all swaps.",
    swapActive: "Active",
    swapReset: "Reset",
    swapDone: "Done",
    swapConnectPrompt: "Connect your wallet to start swapping",
    swapEmptyTokens: "No tokens available to swap",
    swapEmptyTokensHint: "Deposit tokens to your wallet first",
    swapFrom: "From",
    swapTo: "To",
    swapBalance: "Balance: {amount}",
    swapSelectToken: "Select Token",
    swapSearchPlaceholder: "Search tokens...",
    swapNoTokensMatch: "No tokens match",
    swapExecute: "Swap",
    swapSuccess: "Swap successful",
    swapReceived: "Received",
    swapVia: "via {provider}",
    swapSeeDetails: "See details",
    swapRate: "Rate",
    swapPriceImpact: "Price Impact",
    swapMinReceived: "Min. Received",
    swapNetworkFee: "Network Fee",
    swapRoute: "Route",
    swapConfirm: "Confirm Swap",
    swapSwapping: "Swapping...",
    swapEnterAmount: "Enter Amount",
    swapInsufficientBalance: "Insufficient Balance",
    swapNoRoute: "No Route Available",
    dashNetWorth: "Net Worth",
    dashWalletAge: "Wallet Age",
    dashDay: "Day",
    dashDays: "Days",
    dashSupplied: "Supplied",
    dashBorrowed: "Borrowed",
    dashNoSupply: "No supply positions",
    dashNoDebt: "No debt positions",
    dashNetPosition: "Net Position",
    dashHealth: "Health",
    dashToken: "Token",
    dashUnderlying: "Underlying",
    dashNotAvailable: "Not available",
    dashUtilizedBalance: "Utilized Balance",
    dashWalletBalance: "Wallet Balance",
    dashNoWalletConnected: "No Wallet Connected",
    dashLiquidityPositions: "Liquidity Positions",
    dashDefiPositions: "DeFi Positions",
    dashNetWorthUser: "{username}'s net worth",
    leaderError: "Unable to load leaderboard right now.",
    leaderRank: "Rank",
    leaderUser: "User",
    leaderAddress: "Address",
    leaderXP: "XP",
    leaderLevel: "Level",
    leaderAnonymous: "Anonymous",
    leaderProfileSet: "Profile set",
    leaderNoUsername: "No username set",
    searchErrorEmpty: "Please enter a wallet address",
    searchErrorInvalid: "Invalid wallet address format",
    settingsSaved: "Settings saved successfully!",
    settingsResetConfirm: "Are you sure you want to reset all settings to default?",
    profileLoading: "Loading profile...",
    profilePfpHint: "Click your avatar to choose PFP. Level {level} can select only unlocked cards.",
    profileSelectPfp: "Select Profile Picture",
    profileMigrationNote: "Older profiles may trigger one wallet signature during save or delete to recover legacy edit permissions. No transaction is sent.",
    profileToday: "Today",
    swapTxDetails: "Transaction details",
    swapNoDetails: "No recent swap details found.",
    swapBackToSwap: "Back to Swap",
    swapRouteLabel: "{provider} route",
    swapCompleted: "Swap completed",
    swapNetworkCost: "Network cost",
    swapTrxHash: "Trx hash",
    swapOpenExplorer: "Open ↗",
    swapUnavailable: "Unavailable",
    swapContactSupport: "Contact support",
    dashConnectPortfolio: "Connect wallet to view your portfolio",
    dashNoTokens: "No tokens found in this wallet",
    dashNoDefi: "No active DeFi positions found",
    dashConnectDefi: "Connect wallet to view DeFi positions",
    dashNoLiquidity: "No liquidity positions found",
    dashConnectLiquidity: "Connect wallet to view liquidity positions",
    dashAnonymousUser: "Anonymous User",
    dashEditProfile: "Edit Profile",
    dashCurrentLevel: "Current Level",
    dashExpPoints: "Experience Points",
    dashCollectedBadges: "Collected Badges",
    dashLoadingBadges: "Loading badges...",
    dashOwned: "Owned",
    dashNotOwned: "Not owned",
    dashNoOnchainBadges: "No on-chain badges",
    dashNoBadgesEarned: "No badges earned yet. Mint badges to level up!",
    badgesAlmostThere: "Almost there!",
    badgesKeepGoing: "Keep going",
    badgesCampaignEnded: "This badge campaign has ended",
    badgesContactAdmin: "Contact admin to enable claiming",
    badgesScanResults: "Scan complete! Found {count} new eligible badges.",
    badgesScanFailed: "Deep scan failed. Try again in a moment.",
    badgesMintSuccessSyncFail: "Badge minted successfully but XP sync failed. Your XP will update shortly.",
    badgesSyncAttemptsFailed: "Sync failed after multiple attempts.",
    badgesShareTitle: "{name} achievement",
    badgesShareSuccess: "Achievement details copied to clipboard.",
    badgesShareNotSupported: "Sharing is not supported on this browser.",
    badgesShareError: "Could not share this achievement right now.",
    badgesDescriptionFallback: "Complete this challenge to unlock the achievement.",
    badgesPublishing: "Publishing on-chain",
    badgesAttesting: "Attesting…",
    badgesAttestationFailed: "Attestation unavailable",
    badgesConnectToClaim: "Please connect your wallet to claim badges",
    badgesClientLoading: "Movement client is still loading. Please try again in a moment.",
    badgesNotPublished: "Badge is not yet published on-chain. Please wait for admin to publish this SBT.",
    badgesMintAuthFailed: "Could not obtain mint authorization from server",
    badgesClaimSuccess: '"{badgeName}" badge claimed!',
    badgesConnectPrompt: "Connect your wallet to view your badge progress and claim earned badges.",
    badgesNoBadgesAvailable: "No badges available yet",
    badgesNoExpired: "No expired badges yet.",
    badgesNoActive: "No active badges yet.",
    badgesAttestationNote: "You're eligible! On-chain attestation is being processed automatically — the Claim button will appear shortly.",
    badgesAttestationFailedNote: "You're eligible, but the on-chain attestation service isn't available right now (the badge may not be configured on-chain yet). Contact the admin to enable claiming.",
    profileNoBioGuest: "This user has not added a bio yet",
  },
  zh: {
    navPortfolio: "投资组合",
    navSwap: "兑换",
    navBadges: "徽章",
    navLeaderboard: "排行榜",
    navMore: "更多",
    menuSupport: "支持",
    menuTheme: "主题",
    menuSettings: "设置",
    menuResources: "资源",
    searchPlaceholder: "搜索地址 / 用户名 / move id",
    recentSearches: "最近搜索",
    searchBlockchain: "正在搜索链上数据...",
    noProfilesFound: "未找到资料。请输入有效的 0x 地址进行链上搜索。",
    lookupOnChain: "在链上查询 {address}",
    walletAddress: "钱包地址",
    onChain: "链上",
    profile: "资料",
    address: "地址",
    connectWallet: "连接钱包",
    disconnect: "断开连接",
    settingsTitle: "设置",
    settingsSubtitle: "自定义你的投资组合体验",
    backToPortfolio: "返回投资组合",
    display: "显示",
    currency: "货币",
    currencyDescription: "选择你偏好的货币",
    theme: "主题",
    themeDescription: "选择主题偏好",
    language: "语言",
    languageDescription: "选择语言",
    hidePositions: "隐藏仓位",
    hidePositionsDescription: "隐藏低于指定美元阈值的 DeFi 和 LP 仓位",
    notifications: "通知",
    enableNotifications: "启用通知",
    enableNotificationsDescription: "接收投资组合更新",
    priceAlerts: "价格提醒",
    priceAlertsDescription: "接收显著价格变化提醒",
    advanced: "高级",
    showTestnet: "显示测试网",
    showTestnetDescription: "在投资组合中包含测试网代币",
    resetDefault: "重置为默认",
    saveSettings: "保存设置",
    dark: "深色",
    light: "浅色",
    auto: "自动",
    english: "英语",
    chinese: "中文",
    korean: "韩语",
    turkish: "土耳其语",
    portfolioTabWalletBalance: "钱包余额",
    portfolioTabDefiPositions: "DeFi 仓位",
    portfolioTabLp: "LP",
    portfolioTabTrxHistory: "交易历史",
    portfolioTransactionHistory: "交易历史",
    badgesTitle: "徽章",
    badgesSubtitle: "通过参与 Movement 网络获得 SBT 成就。",
    badgesAchievements: "成就",
    badgesEarned: "已获得 {total} 中的 {earned}",
    badgesDeepScan: "深度扫描钱包",
    badgesScanning: "⚡ 正在扫描网络...",
    badgesRefresh: "刷新",
    badgesActive: "有效",
    badgesExpired: "已过期",
    badgesCompleted: "已完成",
    badgesCompletedNote: "成就每周更新一次。",
    badgesIncomplete: "未完成",
    badgesIncompleteNote: "继续交易以解锁更多。",
    badgesChecking: "正在检查资格...",
    badgesEligible: "符合资格",
    badgesClaim: "领取徽章",
    badgesClaiming: "正在领取...",
    badgesOwned: "你已拥有此徽章 ✓",
    badgesLocked: "未解锁",
    badgesNotEligible: "尚未符合资格",
    badgesRecheck: "重新检查",
    badgesRetry: "重试",
    badgesCheckFailed: "检查失败 — 请重试",
    badgesShare: "分享成就",
    badgesReadyToClaim: "准备领取",
    badgesInProgress: "进行中",
    swapTitle: "兑换",
    swapSettings: "兑换设置",
    swapMosaicExec: "Mosaic 执行控制",
    swapSlippageTolerance: "滑点容差",
    swapCurrentSlippage: "当前: {slippage}%",
    swapHighSlippageWarning: "高滑点可能导致不利的执行结果。",
    swapAggregator: "聚合器",
    swapProviderCount: "提供者: 1/1",
    swapMosaicAggregatorNote: "Mosaic 是所有兑换的固定聚合器。",
    swapActive: "激活",
    swapReset: "重置",
    swapDone: "完成",
    swapConnectPrompt: "连接钱包开始兑换",
    swapEmptyTokens: "没有可兑换的代币",
    swapEmptyTokensHint: "请先将代币存入钱包",
    swapFrom: "从",
    swapTo: "到",
    swapBalance: "余额: {amount}",
    swapSelectToken: "选择代币",
    swapSearchPlaceholder: "搜索代币...",
    swapNoTokensMatch: "没有匹配的代币",
    swapExecute: "兑换",
    swapSuccess: "兑换成功",
    swapReceived: "已收到",
    swapVia: "通过 {provider}",
    swapSeeDetails: "查看详情",
    swapRate: "汇率",
    swapPriceImpact: "价格影响",
    swapMinReceived: "最低收到",
    swapNetworkFee: "网络费用",
    swapRoute: "路由",
    swapConfirm: "确认兑换",
    swapSwapping: "正在兑换...",
    swapEnterAmount: "输入金额",
    swapInsufficientBalance: "余额不足",
    swapNoRoute: "无可用路由",
    dashNetWorth: "净资产",
    dashWalletAge: "钱包年龄",
    dashDay: "天",
    dashDays: "天",
    dashSupplied: "已供应",
    dashBorrowed: "已借入",
    dashNoSupply: "暂无供应仓位",
    dashNoDebt: "暂无债务仓位",
    dashNetPosition: "净仓位",
    dashHealth: "健康度",
    dashToken: "代币",
    dashUnderlying: "底层资产",
    dashNotAvailable: "不可用",
    dashUtilizedBalance: "已利用余额",
    dashWalletBalance: "钱包余额",
    dashNoWalletConnected: "未连接钱包",
    dashLiquidityPositions: "流动性仓位",
    dashDefiPositions: "DeFi 仓位",
    dashNetWorthUser: "{username} 的净资产",
    leaderError: "目前无法加载排行榜。",
    leaderRank: "排名",
    leaderUser: "用户",
    leaderAddress: "地址",
    leaderXP: "XP",
    leaderLevel: "等级",
    leaderAnonymous: "匿名",
    leaderProfileSet: "已设置资料",
    leaderNoUsername: "未设置用户名",
    searchErrorEmpty: "请输入钱包地址",
    searchErrorInvalid: "钱包地址格式无效",
    settingsSaved: "设置保存成功！",
    settingsResetConfirm: "确定要将所有设置重置为默认吗？",
    profileLoading: "正在加载资料...",
    profilePfpHint: "点击头像选择 PFP。等级 {level} 只能选择已解锁的卡片。",
    profileSelectPfp: "选择个人资料图片",
    profileMigrationNote: "旧资料在保存或删除时可能会触发一次钱包签名，以恢复旧版编辑权限。不会发送任何交易。",
    profileToday: "今天",
    swapTxDetails: "交易详情",
    swapNoDetails: "未找到最近的兑换详情。",
    swapBackToSwap: "返回兑换",
    swapRouteLabel: "{provider} 路由",
    swapCompleted: "兑换已完成",
    swapNetworkCost: "网络费用",
    swapTrxHash: "交易哈希",
    swapOpenExplorer: "打开 ↗",
    swapUnavailable: "不可用",
    swapContactSupport: "联系支持",
    dashConnectPortfolio: "连接钱包以查看您的投资组合",
    dashNoTokens: "此钱包中未发现代币",
    dashNoDefi: "未发现活跃的 DeFi 仓位",
    dashConnectDefi: "连接钱包以查看 DeFi 仓位",
    dashNoLiquidity: "未发现流动性仓位",
    dashConnectLiquidity: "连接钱包以查看流动性仓位",
    dashAnonymousUser: "匿名用户",
    dashEditProfile: "编辑资料",
    dashCurrentLevel: "当前等级",
    dashExpPoints: "经验值",
    dashCollectedBadges: "已收集徽章",
    dashLoadingBadges: "正在加载徽章...",
    dashOwned: "已拥有",
    dashNotOwned: "未拥有",
    dashNoOnchainBadges: "无链上徽章",
    dashNoBadgesEarned: "尚未获得徽章。铸造徽章以升级！",
    badgesAlmostThere: "快要达成了！",
    badgesKeepGoing: "继续加油",
    badgesCampaignEnded: "此徽章活动已结束",
    badgesContactAdmin: "联系管理员以开启领取",
    badgesScanResults: "扫描完成！发现 {count} 个新的符合条件的徽章。",
    badgesScanFailed: "深度扫描失败。请稍后重试。",
    badgesMintSuccessSyncFail: "徽章铸造成功，但 XP 同步失败。您的 XP 将很快更新。",
    badgesSyncAttemptsFailed: "多次尝试后同步依然失败。",
    badgesShareTitle: "{name} 成就",
    badgesShareSuccess: "成就详情已复制到剪贴板。",
    badgesShareNotSupported: "此浏览器不支持分享。",
    badgesShareError: "目前无法分享此成就。",
    badgesDescriptionFallback: "完成此挑战以解锁成就。",
    badgesPublishing: "正在链上发布",
    badgesAttesting: "正在证明...",
    badgesAttestationFailed: "证明不可用",
    badgesConnectToClaim: "请连接钱包以领取徽章",
    badgesClientLoading: "Movement 客户端仍在加载中。请稍后重试。",
    badgesNotPublished: "徽章尚未在链上发布。请等待管理员发布此 SBT。",
    badgesMintAuthFailed: "无法从服务器获取铸造授权",
    badgesClaimSuccess: '“{badgeName}”徽章已领取！',
    badgesConnectPrompt: "连接钱包以查看徽章进度并领取已获得的徽章。",
    badgesNoBadgesAvailable: "尚无可用徽章",
    badgesNoExpired: "尚无过期的徽章。",
    badgesNoActive: "尚无有效的徽章。",
    badgesAttestationNote: "您符合资格！链上证明正在自动处理中 — 领取按钮很快就会出现。",
    badgesAttestationFailedNote: "您符合资格，但链上证明服务目前不可用（徽章可能尚未在链上配置）。请联系管理员开启领取。",
    profileNoBioGuest: "该用户尚未添加简介",
  },
  ko: {
    navPortfolio: "포트폴리오",
    navSwap: "스왑",
    navBadges: "배지",
    navLeaderboard: "리더보드",
    navMore: "더보기",
    menuSupport: "지원",
    menuTheme: "테마",
    menuSettings: "설정",
    menuResources: "리소스",
    searchPlaceholder: "주소 / 사용자명 / move id 검색",
    recentSearches: "최근 검색",
    searchBlockchain: "블록체인 검색 중...",
    noProfilesFound: "프로필을 찾을 수 없습니다. 유효한 0x 주소를 입력해 체인을 검색하세요.",
    lookupOnChain: "체인에서 {address} 조회",
    walletAddress: "지갑 주소",
    onChain: "온체인",
    profile: "프로필",
    address: "주소",
    connectWallet: "지갑 연결",
    disconnect: "연결 해제",
    settingsTitle: "설정",
    settingsSubtitle: "포트폴리오 환경을 맞춤 설정하세요",
    backToPortfolio: "포트폴리오로 돌아가기",
    display: "표시",
    currency: "통화",
    currencyDescription: "선호 통화를 선택하세요",
    theme: "테마",
    themeDescription: "테마 선호도를 선택하세요",
    language: "언어",
    languageDescription: "언어를 선택하세요",
    hidePositions: "포지션 숨기기",
    hidePositionsDescription: "선택한 USD 기준보다 작은 DeFi 및 LP 포지션을 숨깁니다",
    notifications: "알림",
    enableNotifications: "알림 활성화",
    enableNotificationsDescription: "포트폴리오 업데이트를 받습니다",
    priceAlerts: "가격 알림",
    priceAlertsDescription: "중요한 가격 변동 알림을 받습니다",
    advanced: "고급",
    showTestnet: "테스트넷 표시",
    showTestnetDescription: "포트폴리오에 테스트넷 토큰 포함",
    resetDefault: "기본값으로 재설정",
    saveSettings: "설정 저장",
    dark: "다크",
    light: "라이트",
    auto: "자동",
    english: "영어",
    chinese: "중국어",
    korean: "한국어",
    turkish: "터키어",
    portfolioTabWalletBalance: "지갑 잔액",
    portfolioTabDefiPositions: "디파이 포지션",
    portfolioTabLp: "LP",
    portfolioTabTrxHistory: "거래 내역",
    portfolioTransactionHistory: "거래 내역",
    badgesTitle: "배지",
    badgesSubtitle: "Movement 네트워크에 참여하여 SBT 업적을 달성하세요.",
    badgesAchievements: "업적",
    badgesEarned: "{total} 중 {earned} 획득",
    badgesDeepScan: "지갑 정밀 스캔",
    badgesScanning: "⚡ 네트워크 스캔 중...",
    badgesRefresh: "새로고침",
    badgesActive: "활성",
    badgesExpired: "만료됨",
    badgesCompleted: "완료됨",
    badgesCompletedNote: "업적은 매주 업데이트됩니다.",
    badgesIncomplete: "미완료",
    badgesIncompleteNote: "더 많은 업적을 위해 계속 거래하세요.",
    badgesChecking: "자격 확인 중...",
    badgesEligible: "자격 있음",
    badgesClaim: "배지 받기",
    badgesClaiming: "받는 중...",
    badgesOwned: "이 배지를 보유하고 있습니다 ✓",
    badgesLocked: "잠김",
    badgesNotEligible: "아직 자격이 없습니다",
    badgesRecheck: "재확인",
    badgesRetry: "재시도",
    badgesCheckFailed: "확인 실패 — 다시 시도하세요",
    badgesShare: "업적 공유",
    badgesReadyToClaim: "받기 가능",
    badgesInProgress: "진행 중",
    swapTitle: "스왑",
    swapSettings: "스왑 설정",
    swapMosaicExec: "Mosaic 실행 제어",
    swapSlippageTolerance: "슬리피지 허용 오차",
    swapCurrentSlippage: "현재: {slippage}%",
    swapHighSlippageWarning: "높은 슬리피지는 불리한 실행 결과를 초래할 수 있습니다.",
    swapAggregator: "애그리게이터",
    swapProviderCount: "제공자: 1/1",
    swapMosaicAggregatorNote: "Mosaic은 모든 스왑의 고정 애그리게이터입니다.",
    swapActive: "활성",
    swapReset: "초기화",
    swapDone: "완료",
    swapConnectPrompt: "스왑을 시작하려면 지갑을 연결하세요",
    swapEmptyTokens: "스왑 가능한 토큰이 없습니다",
    swapEmptyTokensHint: "먼저 지갑에 토큰을 입금하세요",
    swapFrom: "보내기",
    swapTo: "받기",
    swapBalance: "잔액: {amount}",
    swapSelectToken: "토큰 선택",
    swapSearchPlaceholder: "토큰 검색...",
    swapNoTokensMatch: "일치하는 토큰이 없습니다",
    swapExecute: "스왑",
    swapSuccess: "스왑 성공",
    swapReceived: "받음",
    swapVia: "{provider} 경유",
    swapSeeDetails: "상세 정보",
    swapRate: "교환 비율",
    swapPriceImpact: "가격 영향",
    swapMinReceived: "최소 수령액",
    swapNetworkFee: "네트워크 수수료",
    swapRoute: "경로",
    swapConfirm: "스왑 확인",
    swapSwapping: "스왑 중...",
    swapEnterAmount: "금액 입력",
    swapInsufficientBalance: "잔액 부족",
    swapNoRoute: "사용 가능한 경로 없음",
    dashNetWorth: "순자산",
    dashWalletAge: "지갑 생성 기간",
    dashDay: "일",
    dashDays: "일",
    dashSupplied: "공급됨",
    dashBorrowed: "대출됨",
    dashNoSupply: "공급 포지션 없음",
    dashNoDebt: "부채 포지션 없음",
    dashNetPosition: "순 포지션",
    dashHealth: "건전성",
    dashToken: "토큰",
    dashUnderlying: "기초 자산",
    dashNotAvailable: "사용 가능하지 않음",
    dashUtilizedBalance: "활용 잔액",
    dashWalletBalance: "지갑 잔액",
    dashNoWalletConnected: "지갑 연결 안 됨",
    dashLiquidityPositions: "유동성 포지션",
    dashDefiPositions: "디파이 포지션",
    dashNetWorthUser: "{username}님의 순자산",
    leaderError: "지금은 리더보드를 불러올 수 없습니다.",
    leaderRank: "순위",
    leaderUser: "사용자",
    leaderAddress: "주소",
    leaderXP: "XP",
    leaderLevel: "레벨",
    leaderAnonymous: "익명",
    leaderProfileSet: "프로필 설정됨",
    leaderNoUsername: "사용자명 미설정",
    searchErrorEmpty: "지갑 주소를 입력하세요",
    searchErrorInvalid: "지갑 주소 형식이 올바르지 않습니다",
    settingsSaved: "설정이 성공적으로 저장되었습니다!",
    settingsResetConfirm: "모든 설정을 기본값으로 초기화하시겠습니까?",
    profileLoading: "프로필 불러오는 중...",
    profilePfpHint: "아바타를 클릭해 PFP를 선택하세요. 레벨 {level}은 해제된 카드만 선택할 수 있습니다.",
    profileSelectPfp: "프로필 사진 선택",
    profileMigrationNote: "이전 프로필은 저장하거나 삭제할 때 레거시 편집 권한 복구를 위해 한 번의 지갑 서명이 필요할 수 있습니다. 트랜잭션은 전송되지 않습니다.",
    profileToday: "오늘",
    swapTxDetails: "거래 상세",
    swapNoDetails: "최근 스왑 상세 내역을 찾을 수 없습니다.",
    swapBackToSwap: "스왑으로 돌아가기",
    swapRouteLabel: "{provider} 경로",
    swapCompleted: "스왑 완료됨",
    swapNetworkCost: "네트워크 비용",
    swapTrxHash: "거래 해시",
    swapOpenExplorer: "열기 ↗",
    swapUnavailable: "사용 불가능",
    swapContactSupport: "고객 지원 문의",
    dashConnectPortfolio: "포트폴리오를 보려면 지갑을 연결하세요",
    dashNoTokens: "이 지갑에서 토큰을 찾을 수 없습니다",
    dashNoDefi: "활성 디파이 포지션을 찾을 수 없습니다",
    dashConnectDefi: "디파이 포지션을 보려면 지갑을 연결하세요",
    dashNoLiquidity: "유동성 포지션을 찾을 수 없습니다",
    dashConnectLiquidity: "유동성 포지션을 보려면 지갑을 연결하세요",
    dashAnonymousUser: "익명 사용자",
    dashEditProfile: "프로필 편집",
    dashCurrentLevel: "현재 레벨",
    dashExpPoints: "경험치",
    dashCollectedBadges: "수집한 뱃지",
    dashLoadingBadges: "뱃지 불러오는 중...",
    dashOwned: "보유함",
    dashNotOwned: "보유하지 않음",
    dashNoOnchainBadges: "온체인 뱃지 없음",
    dashNoBadgesEarned: "아직 획득한 뱃지가 없습니다. 뱃지를 민트하고 레벨업하세요!",
    badgesAlmostThere: "거의 다 왔어요!",
    badgesKeepGoing: "조금 더 힘내세요",
    badgesCampaignEnded: "이 배지 캠페인이 종료되었습니다",
    badgesContactAdmin: "관리자에게 문의하여 클레임을 활성화하세요",
    badgesScanResults: "스캔 완료! {count}개의 새로운 획득 가능 배지를 찾았습니다.",
    badgesScanFailed: "정밀 스캔 실패. 잠시 후 다시 시도하세요.",
    badgesMintSuccessSyncFail: "배지 민팅은 성공했으나 XP 동기화에 실패했습니다. 곧 업데이트될 예정입니다.",
    badgesSyncAttemptsFailed: "여러 번의 시도 끝에 동기화가 실패했습니다.",
    badgesShareTitle: "{name} 업적",
    badgesShareSuccess: "업적 상세 정보가 클립보드에 복사되었습니다.",
    badgesShareNotSupported: "이 브라우저에서는 공유 기능을 지원하지 않습니다.",
    badgesShareError: "지금은 이 업적을 공유할 수 없습니다.",
    badgesDescriptionFallback: "이 챌린지를 완료하고 업적을 달성하세요.",
    badgesPublishing: "온체인 게시 중",
    badgesAttesting: "증명 중…",
    badgesAttestationFailed: "증명 불가",
    badgesConnectToClaim: "배지를 받으려면 지갑을 연결하세요",
    badgesClientLoading: "Movement 클라이언트를 불러오는 중입니다. 잠시 후 다시 시도하세요.",
    badgesNotPublished: "배지가 아직 온체인에 게시되지 않았습니다. 관리자가 이 SBT를 게시할 때까지 기다려 주세요.",
    badgesMintAuthFailed: "서버로부터 민팅 권한을 가져올 수 없습니다",
    badgesClaimSuccess: '"{badgeName}" 배지를 획득했습니다!',
    badgesConnectPrompt: "지갑을 연결하여 배지 진행 상황을 확인하고 획득한 배지를 받으세요.",
    badgesNoBadgesAvailable: "사용 가능한 배지가 없습니다",
    badgesNoExpired: "만료된 배지가 없습니다.",
    badgesNoActive: "활성 배지가 없습니다.",
    badgesAttestationNote: "조건을 충족했습니다! 온체인 증명이 자동으로 처리되고 있습니다. 곧 받기 버튼이 나타납니다.",
    badgesAttestationFailedNote: "조건을 충족했으나 온체인 증명 서비스를 현재 사용할 수 없습니다(배지가 온체인에 아직 설정되지 않았을 수 있습니다). 받기 활성화를 위해 관리자에게 문의하세요.",
    profileNoBioGuest: "이 사용자는 아직 자기소개를 추가하지 않았습니다",
  },
  tr: {
    navPortfolio: "PORTFÖY",
    navSwap: "TAKAS",
    navBadges: "ROZETLER",
    navLeaderboard: "LİDERLİK",
    navMore: "DAHA FAZLA",
    menuSupport: "Destek",
    menuTheme: "Tema",
    menuSettings: "Ayarlar",
    menuResources: "Kaynaklar",
    searchPlaceholder: "Adres / kullanıcı adı / move id ara",
    recentSearches: "Son Aramalar",
    searchBlockchain: "Zincir aranıyor...",
    noProfilesFound: "Profil bulunamadı. Zinciri aramak için geçerli bir 0x adresi girin.",
    lookupOnChain: "Zincirde {address} ara",
    walletAddress: "Cüzdan adresi",
    onChain: "Zincirde",
    profile: "Profil",
    address: "Adres",
    connectWallet: "Cüzdanı Bağla",
    disconnect: "Bağlantıyı Kes",
    settingsTitle: "Ayarlar",
    settingsSubtitle: "Portföy deneyimini özelleştir",
    backToPortfolio: "Portföye Dön",
    display: "Görünüm",
    currency: "Para Birimi",
    currencyDescription: "Tercih ettiğiniz para birimini seçin",
    theme: "Tema",
    themeDescription: "Tema tercihinizi seçin",
    language: "Dil",
    languageDescription: "Dilinizi seçin",
    hidePositions: "Pozisyonları Gizle",
    hidePositionsDescription: "Seçilen USD eşiğinin altındaki DeFi ve LP pozisyonlarını gizle",
    notifications: "Bildirimler",
    enableNotifications: "Bildirimleri Etkinleştir",
    enableNotificationsDescription: "Portföy güncellemelerini alın",
    priceAlerts: "Fiyat Uyarıları",
    priceAlertsDescription: "Önemli fiyat değişimlerinde bildirim alın",
    advanced: "Gelişmiş",
    showTestnet: "Testnet Göster",
    showTestnetDescription: "Portföyde testnet tokenlarını göster",
    resetDefault: "Varsayılana Sıfırla",
    saveSettings: "Ayarları Kaydet",
    dark: "Koyu",
    light: "Açık",
    auto: "Otomatik",
    english: "İngilizce",
    chinese: "Çince",
    korean: "Korece",
    turkish: "Türkçe",
    portfolioTabWalletBalance: "Cüzdan Bakiyesi",
    portfolioTabDefiPositions: "DeFi Pozisyonları",
    portfolioTabLp: "LP",
    portfolioTabTrxHistory: "İşlem Geçmişi",
    portfolioTransactionHistory: "İşlem Geçmişi",
    badgesTitle: "Rozetler",
    badgesSubtitle: "Movement Network'e katılarak SBT başarıları kazanın.",
    badgesAchievements: "Başarılar",
    badgesEarned: "{earned} / {total} Tamamlandı",
    badgesDeepScan: "Cüzdanımı Derin Tara",
    badgesScanning: "⚡ Ağ Taranıyor...",
    badgesRefresh: "Yenile",
    badgesActive: "Aktif",
    badgesExpired: "Süresi Dolmuş",
    badgesCompleted: "Tamamlandı",
    badgesCompletedNote: "Başarılar haftalık olarak güncellenir.",
    badgesIncomplete: "Tamamlanmamış",
    badgesIncompleteNote: "Daha fazlasını açmak için işlem yapmaya devam edin.",
    badgesChecking: "Uygunluk kontrol ediliyor...",
    badgesEligible: "Uygun",
    badgesClaim: "Rozeti Al",
    badgesClaiming: "Alınıyor...",
    badgesOwned: "Bu rozete sahipsiniz ✓",
    badgesLocked: "Kilitli",
    badgesNotEligible: "Henüz uygun değil",
    badgesRecheck: "Yeniden Kontrol Et",
    badgesRetry: "Tekrar Dene",
    badgesCheckFailed: "Kontrol başarısız — tekrar deneyin",
    badgesShare: "Başarıyı Paylaş",
    badgesReadyToClaim: "Almaya hazır",
    badgesInProgress: "Devam ediyor",
    swapTitle: "Takas",
    swapSettings: "Takas Ayarları",
    swapMosaicExec: "Mosaic yürütme kontrolleri",
    swapSlippageTolerance: "Kayma Toleransı",
    swapCurrentSlippage: "Mevcut: %{slippage}",
    swapHighSlippageWarning: "Yüksek kayma, olumsuz yürütme sonuçlarına neden olabilir.",
    swapAggregator: "Aggregator",
    swapProviderCount: "Sağlayıcı: 1/1",
    swapMosaicAggregatorNote: "Mosaic, tüm takaslar için sabit birleştiricidir.",
    swapActive: "Aktif",
    swapReset: "Sıfırla",
    swapDone: "Tamam",
    swapConnectPrompt: "Takas yapmaya başlamak için cüzdanınızı bağlayın",
    swapEmptyTokens: "Takas edilecek token yok",
    swapEmptyTokensHint: "Önce cüzdanınıza token yatırın",
    swapFrom: "Gönderilen",
    swapTo: "Alınan",
    swapBalance: "Bakiye: {amount}",
    swapSelectToken: "Token Seç",
    swapSearchPlaceholder: "Token ara...",
    swapNoTokensMatch: "Eşleşen token yok",
    swapExecute: "Takas Yap",
    swapSuccess: "Takas başarılı",
    swapReceived: "Alındı",
    swapVia: "{provider} üzerinden",
    swapSeeDetails: "Detayları gör",
    swapRate: "Oran",
    swapPriceImpact: "Fiyat Etkisi",
    swapMinReceived: "Min. Alınan",
    swapNetworkFee: "Ağ Ücreti",
    swapRoute: "Rota",
    swapConfirm: "Takası Onayla",
    swapSwapping: "Takas yapılıyor...",
    swapEnterAmount: "Miktar Girin",
    swapInsufficientBalance: "Yetersiz Bakiye",
    swapNoRoute: "Rota Bulunamadı",
    dashNetWorth: "Net Değer",
    dashWalletAge: "Cüzdan Yaşı",
    dashDay: "Gün",
    dashDays: "Gün",
    dashSupplied: "Sağlanan",
    dashBorrowed: "Ödünç Alınan",
    dashNoSupply: "Sağlanan pozisyon yok",
    dashNoDebt: "Borç pozisyonu yok",
    dashNetPosition: "Net Pozisyon",
    dashHealth: "Sağlık",
    dashToken: "Token",
    dashUnderlying: "Dayanak Varlık",
    dashNotAvailable: "Mevcut değil",
    dashUtilizedBalance: "Kullanılan Bakiye",
    dashWalletBalance: "Cüzdan Bakiyesi",
    dashNoWalletConnected: "Cüzdan Bağlı Değil",
    dashLiquidityPositions: "Likidite Pozisyonları",
    dashDefiPositions: "DeFi Pozisyonları",
    dashNetWorthUser: "{username} net varlığı",
    leaderError: "Liderlik tablosu şu an yüklenemiyor.",
    leaderRank: "Sıra",
    leaderUser: "Kullanıcı",
    leaderAddress: "Adres",
    leaderXP: "XP",
    leaderLevel: "Seviye",
    leaderAnonymous: "Anonim",
    leaderProfileSet: "Profil ayarlandı",
    leaderNoUsername: "Kullanıcı adı ayarlanmadı",
    searchErrorEmpty: "Lütfen bir cüzdan adresi girin",
    searchErrorInvalid: "Geçersiz cüzdan adresi formatı",
    settingsSaved: "Ayarlar başarıyla kaydedildi!",
    settingsResetConfirm: "Tüm ayarları varsayılana sıfırlamak istediğinizden emin misiniz?",
    profileLoading: "Profil yükleniyor...",
    profilePfpHint: "PFP seçmek için avatarınıza tıklayın. Seviye {level} yalnızca kilidi açılmış kartları seçebilir.",
    profileSelectPfp: "Profil Resmi Seç",
    profileMigrationNote: "Eski profiller, eski düzenleme izinlerini kurtarmak için kaydetme veya silme sırasında bir cüzdan imzası tetikleyebilir. Herhangi bir işlem gönderilmez.",
    profileToday: "Bugün",
    swapTxDetails: "İşlem detayları",
    swapNoDetails: "Yakın zamanda takas detayı bulunamadı.",
    swapBackToSwap: "Takasa Geri Dön",
    swapRouteLabel: "{provider} rotası",
    swapCompleted: "Takas tamamlandı",
    swapNetworkCost: "Ağ maliyeti",
    swapTrxHash: "İşlem özeti (hash)",
    swapOpenExplorer: "Aç ↗",
    swapUnavailable: "Mevcut değil",
    swapContactSupport: "Destekle iletişime geç",
    dashConnectPortfolio: "Portföyünüzü görüntülemek için cüzdanınızı bağlayın",
    dashNoTokens: "Bu cüzdanda token bulunamadı",
    dashNoDefi: "Aktif DeFi pozisyonu bulunamadı",
    dashConnectDefi: "DeFi pozisyonlarını görüntülemek için cüzdanınızı bağlayın",
    dashNoLiquidity: "Likidite pozisyonu bulunamadı",
    dashConnectLiquidity: "Likidite pozisyonlarını görüntülemek için cüzdanınızı bağlayın",
    dashAnonymousUser: "Anonim Kullanıcı",
    dashEditProfile: "Profili Düzenle",
    dashCurrentLevel: "Mevcut Seviye",
    dashExpPoints: "Deneyim Puanları",
    dashCollectedBadges: "Toplanan Rozetler",
    dashLoadingBadges: "Rozetler yükleniyor...",
    dashOwned: "Sahip Olunan",
    dashNotOwned: "Sahip Olunmayan",
    dashNoOnchainBadges: "On-chain rozet yok",
    dashNoBadgesEarned: "Henüz rozet kazanılmadı. Seviye atlamak için rozetleri naneleyin!",
    badgesAlmostThere: "Neredeyse bitti!",
    badgesKeepGoing: "Devam et",
    badgesCampaignEnded: "Bu rozet kampanyası sona erdi",
    badgesContactAdmin: "Alımı etkinleştirmek için yöneticiyle iletişime geçin",
    badgesScanResults: "Tarama tamamlandı! {count} yeni uygun rozet bulundu.",
    badgesScanFailed: "Derin tarama başarısız oldu. Birazdan tekrar deneyin.",
    badgesMintSuccessSyncFail: "Rozet başarıyla darp edildi ancak XP senkronizasyonu başarısız oldu. XP'niz kısa süre içinde güncellenecektir.",
    badgesSyncAttemptsFailed: "Birden fazla denemeden sonra senkronizasyon başarısız oldu.",
    badgesShareTitle: "{name} başarısı",
    badgesShareSuccess: "Başarı detayları panoya kopyalandı.",
    badgesShareNotSupported: "Paylaşım bu tarayıcıda desteklenmiyor.",
    badgesShareError: "Bu başarı şu anda paylaşılamıyor.",
    badgesDescriptionFallback: "Başarıyı kilidini açmak için bu görevi tamamlayın.",
    badgesPublishing: "Zincir üzerinde yayınlanıyor",
    badgesAttesting: "Onaylanıyor…",
    badgesAttestationFailed: "Onaylama mevcut değil",
    badgesConnectToClaim: "Rozetleri almak için lütfen cüzdanınızı bağlayın",
    badgesClientLoading: "Movement istemcisi hala yükleniyor. Lütfen birazdan tekrar deneyin.",
    badgesNotPublished: "Rozet henüz zincir üzerinde yayınlanmadı. Lütfen yöneticinin bu SBT'yi yayınlamasını bekleyin.",
    badgesMintAuthFailed: "Sunucudan darp yetkisi alınamadı",
    badgesClaimSuccess: '"{badgeName}" rozeti alındı!',
    badgesConnectPrompt: "Rozet ilerlemenizi görmek ve kazanılan rozetleri almak için cüzdanınızı bağlayın.",
    badgesNoBadgesAvailable: "Henüz rozet mevcut değil",
    badgesNoExpired: "Henüz süresi dolmuş rozet yok.",
    badgesNoActive: "Henüz aktif rozet yok.",
    badgesAttestationNote: "Uygunluk durumunuz onaylandı! Zincir üstü onay otomatik olarak işleniyor — Talep Et butonu kısa süre içinde görünecektir.",
    badgesAttestationFailedNote: "Uygunsunuz ancak zincir üstü onay hizmeti şu anda kullanılamıyor (rozet henüz zincir üstü yapılandırılmamış olabilir). Talebi etkinleştirmek için yöneticiyle iletişime geçin.",
    profileNoBioGuest: "Bu kullanıcı henüz bir biyografi eklemedi",
  },
};

export const t = (language, key, vars = {}) => {
  const lang = normalizeLanguage(language);
  const value = TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.en[key] ?? key;

  return Object.entries(vars).reduce(
    (result, [varKey, varValue]) => result.replaceAll(`{${varKey}}`, String(varValue)),
    value
  );
};
