[package]
name = "subscription_manager"
version = "1.0.0"
authors = []

[addresses]
subscription_manager = "0x5c2bdc5b4926bd545d39c8caca4c96cffca19d707bda7f8bffd8602c1eaf1133" # Same deployer as swap_router for now

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"
